libnisdb: control reaches end of non-void function
db_index.cc: In member function 'int db_index::dump(char*)':
db_index.cc:332:35: error: control reaches end of non-void function [-Werror=return-type]
  pickle_index f(file, PICKLE_WRITE);
                                   ^
db_table.cc: In member function 'int db_table::dump(char*)':
db_table.cc:1110:35: error: control reaches end of non-void function [-Werror=return-type]
  pickle_table f(file, PICKLE_WRITE);   /* may need to use APPEND mode */
                                   ^
nis_db.cc: In function 'db_status db_abort_merge_dict()':
nis_db.cc:277:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1plus: all warnings being treated as errors